.\" Pipe this output to groff -m man -K utf8 -T utf8 | less -R
.\"
.mso an.tmac
.TH "DUNE-PROMOTE" 1 "" "Dune 3.24.2" "Dune Manual"
.\" Disable hyphenation and ragged-right
.nh
.ad l
.SH NAME
.P
dune\N'45'promote \N'45' An alias for \fBpromotion apply\fR\N'46'
.SH SYNOPSIS
.P
\fBdune promote\fR [\fB\N'45'\N'45'build\N'45'info\fR] [\fB\N'45'\N'45'file\fR] [\fIOPTION\fR]… [\fIFILE\fR]…
.SH DESCRIPTION
.P
\fBdune\fR\fB promote\fR is an alias for \fBdune\fR\fB promotion apply\fR\N'46'
.P
See \fBdune\fR\fB promotion apply \N'45'\N'45'help\fR for details\N'46'
.SH OPTIONS
.TP 4
\fB\N'45'\N'45'build\N'45'info\fR
Show build information\N'46'
.TP 4
\fB\N'45'\N'45'file\fR
Require each FILE argument to match exactly\N'46'
.SH COMMON OPTIONS
.P
These options are common to all commands\N'46'
.TP 4
\fB\N'45'\N'45'debug\N'45'backtraces\fR
Always print exception backtraces\N'46'
.TP 4
\fB\N'45'\N'45'help\fR[=\fIFMT\fR] (default=\fBauto\fR)
Show this help in format \fIFMT\fR\N'46' The value \fIFMT\fR must be one of \fBauto\fR, \fBpager\fR, \fBgroff\fR or \fBplain\fR\N'46' With \fBauto\fR, the format is \fBpager\fR or \fBplain\fR whenever the \fBTERM\fR env var is \fBdumb\fR or undefined\N'46'
.TP 4
\fB\N'45'\N'45'version\fR
Show version information\N'46'
.SH MORE HELP
.P
Use `\fBdune\fR \fICOMMAND\fR \N'45'\N'45'help\N'39' for help on a single command\N'46'
.SH EXIT STATUS
.P
\fBdune promote\fR exits with:
.TP 4
0
on success\N'46'
.TP 4
1
if an error happened\N'46'
.TP 4
130
if it was interrupted by a signal\N'46'
.SH BUGS
.P
Check bug reports at https://github\N'46'com/ocaml/dune/issues
.SH SEE ALSO
.P
dune(1)