lib: [
  "_build/install/default/lib/treelib/META"
  "_build/install/default/lib/treelib/dune-package"
  "_build/install/default/lib/treelib/nodedef.ml"
  "_build/install/default/lib/treelib/opam"
  "_build/install/default/lib/treelib/treedef.ml"
  "_build/install/default/lib/treelib/treelib.a"
  "_build/install/default/lib/treelib/treelib.cma"
  "_build/install/default/lib/treelib/treelib.cmi"
  "_build/install/default/lib/treelib/treelib.cmt"
  "_build/install/default/lib/treelib/treelib.cmx"
  "_build/install/default/lib/treelib/treelib.cmxa"
  "_build/install/default/lib/treelib/treelib.ml"
  "_build/install/default/lib/treelib/treelib__Nodedef.cmi"
  "_build/install/default/lib/treelib/treelib__Nodedef.cmt"
  "_build/install/default/lib/treelib/treelib__Nodedef.cmx"
  "_build/install/default/lib/treelib/treelib__Treedef.cmi"
  "_build/install/default/lib/treelib/treelib__Treedef.cmt"
  "_build/install/default/lib/treelib/treelib__Treedef.cmx"
]
libexec: [
  "_build/install/default/lib/treelib/treelib.cmxs"
]
bin: [
  "_build/install/default/bin/tree"
]
